theme: jekyll-theme-midnight
# paginator: 10
# paginator_num: "/blog/page:num/"

docs_list_title: Back to Menu
docs:

- title: Home
  url: clevertrevor.me/index.html
  
- title: Blog
  url: clevertrevor.me/Blog/index.html
